
public class Menu extends javax.swing.JFrame {

    public Menu(){
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {


        buttonGroup1 = new javax.swing.ButtonGroup();
        checkbox1 = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DefaultModeButton = new javax.swing.JButton();
        LeaderboardButton = new javax.swing.JButton();
        QuotesModeButton = new javax.swing.JButton();
        SuddenDeathButton = new javax.swing.JButton();
        WordsModeButton = new javax.swing.JButton();
        TimedModeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogOutJButton = new javax.swing.JButton();
        Profile = new javax.swing.JButton();

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText(" TYPHOON");

        DefaultModeButton.setBackground(new java.awt.Color(0, 153, 153));
        DefaultModeButton.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        DefaultModeButton.setForeground(new java.awt.Color(255, 255, 204));
        DefaultModeButton.setText("Default Mode");
        DefaultModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultModeButtonActionPerformed(evt);
            }
        });

        LeaderboardButton.setBackground(new java.awt.Color(0, 153, 153));
        LeaderboardButton.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LeaderboardButton.setForeground(new java.awt.Color(255, 255, 204));
        LeaderboardButton.setText("Leaderboard");

        QuotesModeButton.setBackground(new java.awt.Color(0, 153, 153));
        QuotesModeButton.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        QuotesModeButton.setForeground(new java.awt.Color(255, 255, 204));
        QuotesModeButton.setText("Quotes Mode");
        QuotesModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuotesModeButtonActionPerformed(evt);
            }
        });

        SuddenDeathButton.setBackground(new java.awt.Color(0, 153, 153));
        SuddenDeathButton.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SuddenDeathButton.setForeground(new java.awt.Color(255, 255, 204));
        SuddenDeathButton.setText("Sudden Death");
        SuddenDeathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuddenDeathButtonActionPerformed(evt);
            }
        });

        WordsModeButton.setBackground(new java.awt.Color(0, 153, 153));
        WordsModeButton.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        WordsModeButton.setForeground(new java.awt.Color(255, 255, 204));
        WordsModeButton.setText("Words Mode");
        WordsModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WordsModeButtonActionPerformed(evt);
            }
        });

        TimedModeButton.setBackground(new java.awt.Color(0, 153, 153));
        TimedModeButton.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        TimedModeButton.setForeground(new java.awt.Color(255, 255, 204));
        TimedModeButton.setText("Timed Mode");
        TimedModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimedModeButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("copyright © company name All rights reserved");

        jLabel2.setBackground(new java.awt.Color(255, 255, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("WELCOME TO");

        LogOutJButton.setBackground(new java.awt.Color(255, 255, 255));
        LogOutJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogOutJButton.setForeground(new java.awt.Color(255, 51, 51));
        LogOutJButton.setText("LOG OUT");
        LogOutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutJButtonActionPerformed(evt);
            }
        });

        Profile.setBackground(new java.awt.Color(0, 153, 153));
        Profile.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Profile.setForeground(new java.awt.Color(255, 255, 204));
        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(219, 219, 219)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(SuddenDeathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(QuotesModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(WordsModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TimedModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(DefaultModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(279, 279, 279)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(161, 161, 161)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LeaderboardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(86, 229, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(LogOutJButton)
                                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DefaultModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TimedModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(WordsModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(QuotesModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SuddenDeathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LeaderboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(LogOutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(311, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void TimedModeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        TimedMode TimedModeFrame = new TimedMode();
        TimedModeFrame.setVisible(true);
        TimedModeFrame.setLocationRelativeTo(null);
        this.dispose();
    }

    private void DefaultModeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new MainGame(3, "dictionary.txt", 100, "Default Mode").setVisible(true);
        this.dispose();
    }

    private void WordsModeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        WordsMode WordsModeFrame = new WordsMode();
        WordsModeFrame.setVisible(true);
        WordsModeFrame.setLocationRelativeTo(null);
        this.dispose();
    }

    private void QuotesModeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new MainGame(30, "quote.txt", 15, "Quotes Mode").setVisible(true);
        this.dispose();
    }

    private void LogOutJButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Profile ProfileFrame = new Profile();
        ProfileFrame.setVisible(true);
        ProfileFrame.setLocationRelativeTo(null);
        this.dispose();
    }

    private void SuddenDeathButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new MainGame(30,"dictionary.txt",40,3).setVisible(true);
        this.dispose();
    }

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton DefaultModeButton;
    private javax.swing.JButton LeaderboardButton;
    private javax.swing.JButton LogOutJButton;
    private javax.swing.JButton Profile;
    private javax.swing.JButton QuotesModeButton;
    private javax.swing.JButton SuddenDeathButton;
    private javax.swing.JButton TimedModeButton;
    private javax.swing.JButton WordsModeButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}